name=VCAN2515
version=3.1.0
author=Sven Rosvall <sven@rosvall.ie>
maintainer=Sven Rosvall <sven@rosvall.ie>
sentence=CAN2515 driver for VLCB library
paragraph=Implements functionality required to create a VLCB module based on MCP2515 and MCP2562 ICs
category=Communication
url=https://github.com/SvenRosvall/VLCB-Arduino
architectures=*
includes=CAN2515.h
depends=Streaming,ACAN2515,VLCB
